version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestforge-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      # nestforge:feature:database:postgres
      - postgres
      # nestforge:feature:database:postgres:end
      # nestforge:feature:database:mysql
      - mysql
      # nestforge:feature:database:mysql:end
      - redis
    volumes:
      - ./src:/app/src
    command: npm run start:dev

  # nestforge:feature:database:postgres
  postgres:
    image: postgres:16-alpine
    container_name: nestforge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nestforge
      POSTGRES_PASSWORD: nestforge
      POSTGRES_DB: nestforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # nestforge:feature:database:postgres:end

  # nestforge:feature:database:mysql
  mysql:
    image: mysql:8
    container_name: nestforge-mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: nestforge
      MYSQL_PASSWORD: nestforge
      MYSQL_ROOT_PASSWORD: nestforge
      MYSQL_DATABASE: nestforge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  # nestforge:feature:database:mysql:end

  redis:
    image: redis:7-alpine
    container_name: nestforge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: nestforge-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

  # nestforge:feature:database:postgres
volumes:
  postgres_data:
  # nestforge:feature:database:postgres:end
  # nestforge:feature:database:mysql
volumes:
  mysql_data:
  # nestforge:feature:database:mysql:end