version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestforge-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    # nestforge:feature:database:mongodb
    environment:
      DATABASE_URL: mongodb://mongodb:27017/nestforge?replicaSet=rs0
    # nestforge:feature:database:mongodb:end
    depends_on:
      # nestforge:feature:database:postgres
      - postgres
      # nestforge:feature:database:postgres:end
      # nestforge:feature:database:mysql
      - mysql
      # nestforge:feature:database:mysql:end
      # nestforge:feature:database:mongodb
      - mongodb
      # nestforge:feature:database:mongodb:end
      - redis
    volumes:
      - ./src:/app/src
    command: npm run start:dev

  # nestforge:feature:database:postgres
  postgres:
    image: postgres:16-alpine
    container_name: nestforge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nestforge
      POSTGRES_PASSWORD: nestforge
      POSTGRES_DB: nestforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # nestforge:feature:database:postgres:end

  # nestforge:feature:database:mysql
  mysql:
    image: mysql:8
    container_name: nestforge-mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: nestforge
      MYSQL_PASSWORD: nestforge
      MYSQL_ROOT_PASSWORD: nestforge
      MYSQL_DATABASE: nestforge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  # nestforge:feature:database:mysql:end

  # nestforge:feature:database:mongodb
  mongodb:
    image: mongo:8
    container_name: nestforge-mongodb
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"try { rs.status().ok } catch (error) { rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongodb:27017'}]}).ok }\" | grep 1"]
      interval: 5s
      timeout: 5s
      retries: 10
  # nestforge:feature:database:mongodb:end

  redis:
    image: redis:7-alpine
    container_name: nestforge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: nestforge-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

  # nestforge:feature:database:postgres
volumes:
  postgres_data:
  # nestforge:feature:database:postgres:end
  # nestforge:feature:database:mysql
volumes:
  mysql_data:
  # nestforge:feature:database:mysql:end
  # nestforge:feature:database:mongodb
volumes:
  mongodb_data:
  # nestforge:feature:database:mongodb:end
