version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestforge-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src
    command: npm run start:dev

  postgres:
    image: postgres:16-alpine
    container_name: nestforge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nestforge
      POSTGRES_PASSWORD: nestforge
      POSTGRES_DB: nestforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nestforge-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: nestforge-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

volumes:
  postgres_data:
